"""Editable category definitions for SACHECK.

Add new work categories here. Put optional icon images in:
assets/category_icons/<icon_file>
"""

CATEGORY_ICON_DIR = "assets/category_icons"

CATEGORIES = {
    "Word": {"color": "#2f80ed", "icon": "W", "label": "Word", "icon_file": 
             "word.png"},
    "Excel": {"color": "#21a366", "icon": "X", "label": "Excel", "icon_file": 
              "excel.png"},
    "PDF": {"color": "#e94335", "icon": "PDF", "label": "PDF", "icon_file": 
            "pdf.png"},
    "Figma": {"color": "#a259ff", "icon": "F", "label": "Figma", "icon_file": 
              "figma.png"},
    "Miro": {"color": "#ffd02f", "icon": "M", "label": "Miro", "icon_file": 
             "miro.png"},
    "Canva": {"color": "#ff5fbf", "icon": "C", "label": "Canva", "icon_file": 
              "canva.png"},
    "Slide": {"color": "#f2994a", "icon": "P", "label": "Slide", "icon_file": 
              "slide.png"},
    "Google Sheet": {"color": "#00a884", "icon": "G", "label": "Sheet", "icon_file": 
                     "google_sheet.png"},
    "Diagram": {"color": "#35c7f0", "icon": "D", "label": "Diagram", "icon_file": 
                "diagram.png"},
    "Web": {"color": "#06b6d4", "icon": "WEB", "label": "Web", "icon_file": ""},
    "Project": {"color": "#6366f1", "icon": "PRJ", "label": "Project", "icon_file": ""},
    "Library": {"color": "#8b5cf6", "icon": "LIB", "label": "Library", "icon_file": ""},
    "Image": {"color": "#ec4899", "icon": "IMG", "label": "Image", "icon_file": ""},
    "Video": {"color": "#ef4444", "icon": "VID", "label": "Video", "icon_file": ""},
    "Audio": {"color": "#14b8a6", "icon": "AUD", "label": "Audio", "icon_file": ""},
    "Archive": {"color": "#a16207", "icon": "ZIP", "label": "Archive", "icon_file": ""},
    "Code": {"color": "#334155", "icon": "COD", "label": "Code", "icon_file": ""},
    "Data": {"color": "#0f766e", "icon": "DB", "label": "Data", "icon_file": ""},
    "Link": {"color": "#0ea5e9", "icon": "L", "label": "Link", "icon_file": 
             "link.png"},
    "Other": {"color": "#ffffff", "icon": "O", "label": "Other", "icon_file": 
              "other.png"},
}

EXTENSION_TYPES = {
    # Word / document formats
    ".doc": "Word",
    ".docx": "Word",
    ".docm": "Word",
    ".dot": "Word",
    ".dotx": "Word",
    ".dotm": "Word",
    ".wbk": "Word",
    ".wiz": "Word",
    ".wps": "Word",
    ".wpt": "Word",
    ".wpd": "Word",
    ".rtf": "Word",
    ".odt": "Word",
    ".ott": "Word",
    ".sxw": "Word",
    ".sdw": "Word",
    ".gdoc": "Word",
    ".docxml": "Word",
    ".dochtml": "Word",
    ".mht": "Word",
    ".mhtml": "Word",
    ".fodt": "Word",
    ".uot": "Word",
    ".pages": "Word",

    # Excel / spreadsheet formats
    ".xls": "Excel",
    ".xlsx": "Excel",
    ".xlsm": "Excel",
    ".xlsb": "Excel",
    ".xlt": "Excel",
    ".xltx": "Excel",
    ".xltm": "Excel",
    ".xla": "Excel",
    ".xlam": "Excel",
    ".xlw": "Excel",
    ".xlm": "Excel",
    ".xlk": "Excel",
    ".ods": "Excel",
    ".ots": "Excel",
    ".sxc": "Excel",
    ".dif": "Excel",
    ".slk": "Excel",
    ".csv": "Excel",
    ".tsv": "Excel",
    ".fods": "Excel",
    ".uos": "Excel",
    ".numbers": "Excel",
    ".prn": "Excel",
    ".iqy": "Excel",
    ".oqy": "Excel",
    ".rqy": "Excel",
    ".dqy": "Excel",
    ".gsheet": "Google Sheet",

    # PDF / fixed document formats
    ".pdf": "PDF",
    ".xps": "PDF",
    ".oxps": "PDF",
    ".epub": "PDF",
    ".djvu": "PDF",
    ".djv": "PDF",

    # Figma local/export hints
    ".fig": "Figma",
    ".figjam": "Figma",
    ".sketch": "Figma",
    ".xd": "Figma",

    # PowerPoint / slide formats
    ".ppt": "Slide",
    ".pptx": "Slide",
    ".pptm": "Slide",
    ".pps": "Slide",
    ".ppsx": "Slide",
    ".ppsm": "Slide",
    ".pot": "Slide",
    ".potx": "Slide",
    ".potm": "Slide",
    ".ppa": "Slide",
    ".ppam": "Slide",
    ".sldx": "Slide",
    ".sldm": "Slide",
    ".thmx": "Slide",
    ".key": "Slide",
    ".odp": "Slide",
    ".otp": "Slide",
    ".sxi": "Slide",
    ".gslides": "Slide",
    ".fodp": "Slide",
    ".uop": "Slide",

    # Diagram / flow formats
    ".drawio": "Diagram",
    ".dio": "Diagram",
    ".diagram": "Diagram",
    ".bpmn": "Diagram",
    ".mmd": "Diagram",
    ".mermaid": "Diagram",
    ".puml": "Diagram",
    ".plantuml": "Diagram",
    ".uml": "Diagram",
    ".erd": "Diagram",
    ".vsd": "Diagram",
    ".vsdx": "Diagram",
    ".vsdm": "Diagram",
    ".vdx": "Diagram",
    ".vss": "Diagram",
    ".vssx": "Diagram",
    ".vssm": "Diagram",
    ".vst": "Diagram",
    ".vstx": "Diagram",
    ".vstm": "Diagram",
    ".vsx": "Diagram",
    ".vtx": "Diagram",
    ".gliffy": "Diagram",
    ".mind": "Diagram",
    ".mm": "Diagram",
    ".xmind": "Diagram",
    ".edraw": "Diagram",
    ".edxz": "Diagram",
    ".svg": "Diagram",

    # Web / frontend project files
    ".html": "Web",
    ".htm": "Web",
    ".css": "Web",
    ".scss": "Web",
    ".sass": "Web",
    ".less": "Web",
    ".js": "Web",
    ".mjs": "Web",
    ".cjs": "Web",
    ".ts": "Web",
    ".tsx": "Web",
    ".jsx": "Web",
    ".vue": "Web",
    ".svelte": "Web",
    ".astro": "Web",
    ".json": "Project",
    ".jsonc": "Project",
    ".yaml": "Project",
    ".yml": "Project",
    ".toml": "Project",
    ".md": "Project",
    ".env": "Project",
    ".gitignore": "Project",
    ".py": "Project",
    ".ps1": "Project",
    ".bat": "Project",
    ".cmd": "Project",
    ".sql": "Project",

    # Code / development files
    ".ipynb": "Code",
    ".java": "Code",
    ".cs": "Code",
    ".cpp": "Code",
    ".c": "Code",
    ".h": "Code",
    ".go": "Code",
    ".rs": "Code",
    ".php": "Code",
    ".rb": "Code",
    ".swift": "Code",
    ".kt": "Code",
    ".dart": "Code",
    ".lua": "Code",
    ".sh": "Code",

    # Data files
    ".db": "Data",
    ".sqlite": "Data",
    ".sqlite3": "Data",
    ".mdb": "Data",
    ".accdb": "Data",
    ".parquet": "Data",
    ".feather": "Data",
    ".xml": "Data",

    # Images
    ".png": "Image",
    ".jpg": "Image",
    ".jpeg": "Image",
    ".gif": "Image",
    ".webp": "Image",
    ".bmp": "Image",
    ".tif": "Image",
    ".tiff": "Image",
    ".heic": "Image",
    ".ico": "Image",
    ".psd": "Image",
    ".ai": "Image",

    # Video
    ".mp4": "Video",
    ".mov": "Video",
    ".mkv": "Video",
    ".avi": "Video",
    ".wmv": "Video",
    ".webm": "Video",
    ".m4v": "Video",

    # Audio
    ".mp3": "Audio",
    ".wav": "Audio",
    ".m4a": "Audio",
    ".aac": "Audio",
    ".flac": "Audio",
    ".ogg": "Audio",

    # Archives / packages
    ".zip": "Archive",
    ".rar": "Archive",
    ".7z": "Archive",
    ".tar": "Archive",
    ".gz": "Archive",
    ".bz2": "Archive",
    ".xz": "Archive",
    ".iso": "Archive",

    # Windows web shortcuts
    ".url": "Link",
    ".website": "Link",
    ".lnk": "Link",
}

URL_RULES = [
    {"host": "docs.google.com", "path_prefix": "/spreadsheets", "type": "Google Sheet"},
    {"host": "docs.google.com", "path_prefix": "/presentation", "type": "Slide"},
    {"host": "docs.google.com", "path_prefix": "/document", "type": "Word"},
    {"host": "docs.google.com", "path_prefix": "/drawings", "type": "Diagram"},
    {"host": "drive.google.com", "path_contains": "spreadsheet", "type": "Google Sheet"},
    {"host": "drive.google.com", "path_contains": "presentation", "type": "Slide"},
    {"host": "drive.google.com", "path_contains": "document", "type": "Word"},
    {"host": "sheets.google.com", "type": "Google Sheet"},
    {"host": "slides.google.com", "type": "Slide"},
    {"host_contains": "figma.com", "type": "Figma"},
    {"host_contains": "figjam", "type": "Figma"},
    {"host_contains": "miro.com", "type": "Miro"},
    {"host_contains": "mirostatic.com", "type": "Miro"},
    {"host_contains": "canva.com", "type": "Canva"},
    {"host_contains": "canva.site", "type": "Canva"},
    {"host_contains": "diagrams.net", "type": "Diagram"},
    {"host_contains": "draw.io", "type": "Diagram"},
    {"host_contains": "lucid.app", "type": "Diagram"},
    {"host_contains": "lucidchart.com", "type": "Diagram"},
    {"host_contains": "youtube.com", "type": "Video"},
    {"host_contains": "youtu.be", "type": "Video"},
    {"host_contains": "vimeo.com", "type": "Video"},
    {"host_contains": "loom.com", "type": "Video"},
    {"host_contains": "trello.com", "type": "Project"},
    {"host_contains": "notion.so", "type": "Web"},
    {"host_contains": "notion.site", "type": "Web"},
    {"host_contains": "airtable.com", "type": "Data"},
    {"host_contains": "github.com", "type": "Project"},
    {"host_contains": "gitlab.com", "type": "Project"},
    {"host_contains": "bitbucket.org", "type": "Project"},
    {"host_contains": "vercel.app", "type": "Web"},
    {"host_contains": "netlify.app", "type": "Web"},
    {"host_contains": "localhost", "type": "Web"},
    {"host_contains": "office.com", "path_contains": "word", "type": "Word"},
    {"host_contains": "office.com", "path_contains": "excel", "type": "Excel"},
    {"host_contains": "office.com", "path_contains": "powerpoint", "type": "Slide"},
    {"host_contains": "sharepoint.com", "path_contains": ".doc", "type": "Word"},
    {"host_contains": "sharepoint.com", "path_contains": ".xls", "type": "Excel"},
    {"host_contains": "sharepoint.com", "path_contains": ".ppt", "type": "Slide"},
    {"host_contains": "onedrive.live.com", "path_contains": "word", "type": "Word"},
    {"host_contains": "onedrive.live.com", "path_contains": "excel", "type": "Excel"},
    {"host_contains": "onedrive.live.com", "path_contains": "powerpoint", "type": "Slide"},
]
